Added a disclaimer modal that opens upon user login, requiring the us…
AI-in-Hand/platform pull request #148
Opened 2024-07-10 06:03 UTC by jrtanmoy

…er to click the 'OK, lets go' button to proceed, with no cancel option. Implemented a check using local storage to track if the 'OK' button has been clicked, ensuring the modal does not reappear on subsequent logins unless local storage is cleared.

2024-07-10 17:34 UTC, bonk1t requested changes

2024-07-10 17:34 UTC, bonk1t commented on frontend/src/layouts/mainLayouts.tsx
> +                  d="M18 24C16.34 24 14.9252 23.4148 13.7556 22.2444C12.586 21.074 12.0008 19.6592 12 18C11.9992 16.3408 12.5844 14.926 13.7556 13.7556C14.9268 12.5852 16.3416 12 18 12C19.6584 12 21.
Please don't add SVGs to mainLayouts.tsx. Import it from another module.

2024-07-15 06:51 UTC, jrtanmoy commented on frontend/src/layouts/mainLayouts.tsx
> +                  d="M18 24C16.34 24 14.9252 23.4148 13.7556 22.2444C12.586 21.074 12.0008 19.6592 12 18C11.9992 16.3408 12.5844 14.926 13.7556 13.7556C14.9268 12.5852 16.3416 12 18 12C19.6584 12 21.
@bonk1t, I've refactored the modal logic into a separate disclaimer component and ensured that no SVGs are added directly to mainLayouts.tsx. The disclaimer component is now imported from its own module. Please let me know if there are any other concerns or improvements needed. Thanks!

2024-07-15 20:51 UTC, bonk1t submitted a review, later dismissed

2024-07-17 20:33 UTC, bonk1t approved these changes

2024-07-17 20:34 UTC, merged